name: Release on main

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Tag, Release, and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Read version
        id: pkg
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check
        run: |
          git fetch --tags --force --quiet
          if git rev-parse -q --verify "refs/tags/v${{ steps.pkg.outputs.version }}" >/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.pkg.outputs.version }} already exists. Skipping release."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release (also creates tag)
        if: ${{ steps.check.outputs.exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pkg.outputs.version }}
          name: v${{ steps.pkg.outputs.version }}
          body: |
            Automated release for v${{ steps.pkg.outputs.version }}.
            See CHANGELOG.md for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: ${{ steps.check.outputs.exists == 'false' }}
        run: npm ci

      - name: Publish to npm
        if: ${{ steps.check.outputs.exists == 'false' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
